version: '3'

services:
  mysql:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    restart: always
    environment: 
         MYSQL_ROOT_PASSWORD: 'Gsulax09' # TODO: Change this
         MYSQL_USER: 'brian'
         MYSQL_PASS: 'Gsulax09'
    volumes: 
      - /usr/local/var/mysql/tracker:/var/lib/mysql
  api:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "8080:8080"

volumes:
  node-modules: