# Generated by Django 2.0.5 on 2018-06-11 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intensity', models.CharField(choices=[(1, 'HIIT'), (2, 'Strength'), (3, 'Endurance')], default='Strength', max_length=1)),
                ('duration', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.WorkoutType'),
        ),
    ]
