# Generated by Django 2.0.5 on 2018-07-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.CharField(max_length=50)),
                ('sourceVersion', models.CharField(max_length=50)),
                ('workoutActivityType', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('durationUnit', models.CharField(max_length=10)),
                ('totalDistance', models.IntegerField(default=0)),
                ('totalDistanceUnit', models.CharField(max_length=10)),
                ('totalEnergyBurned', models.IntegerField(default=0)),
                ('totalEnergyBurnedUnit', models.CharField(max_length=10)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
