# Generated by Django 2.0.5 on 2018-06-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.WorkoutIntensity'),
        ),
    ]
