# Generated by Django 2.0.8 on 2018-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='creationDate',
            field=models.CharField(max_length=50),
        ),
    ]
