# Generated by Django 2.0.8 on 2018-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20181125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='creationDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='endDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
